ejercicio=Ejercicio_2.ipynb


pdf: ${ejercicio}
	jupyter nbconvert --output-dir=memoria --to pdf --template excercise $< 


latex: ${ejercicio}
	jupyter nbconvert --output-dir=memoria --to latex --template excercise $< 
